// =========================================================
// AVIPET — inventario.js  v2
// NUEVO: función pública verificarStockProducto() para llamar
//        desde historia.js al agregar servicios/meds
// =========================================================

import { db } from '../firebase-config.js';
import {
  collection, addDoc, doc, getDoc, setDoc, updateDoc,
  deleteDoc, getDocs, query, where, orderBy, serverTimestamp
} from "https://www.gstatic.com/firebasejs/10.7.1/firebase-firestore.js";

const MASTER_KEY = () => window.MASTER_KEY_SISTEMA || "AVIPET2026";

// ─── CARGAR INVENTARIO ───
window.cargarInventario = async () => {
  const lista=document.getElementById('listaInventario');if(!lista)return;
  lista.innerHTML=`<p class="text-center text-blue-500 text-[9px] font-black uppercase italic animate-pulse py-8">⚙️ Cargando inventario...</p>`;
  try{const snap=await getDocs(query(collection(db,"inventario"),orderBy("nombre")));window._inventarioCache=[];snap.forEach(d=>window._inventarioCache.push({id:d.id,...d.data()}));window.renderListaInventario(window._inventarioCache);window.actualizarSelectorProveedores();}
  catch(e){console.error(e);lista.innerHTML=`<p class="text-center text-red-500 text-[9px] font-black uppercase italic py-8">❌ Error de conexión</p>`;}
};

window.renderListaInventario = (items) => {
  const lista=document.getElementById('listaInventario');if(!lista)return;
  if(!items||items.length===0){lista.innerHTML=`<p class="text-center text-slate-400 text-[9px] font-black uppercase italic py-8">Sin productos registrados</p>`;return;}
  lista.innerHTML="";
  items.forEach(p=>{
    const stockBajo=p.cantidadStock<=(p.stockMinimo||3);const colorStock=stockBajo?"text-red-600":"text-emerald-600";
    const badgeStock=stockBajo?`<span class="px-1.5 py-0.5 rounded-full bg-red-100 text-red-600 text-[7px] font-black animate-pulse">⚠️ BAJO</span>`:`<span class="px-1.5 py-0.5 rounded-full bg-emerald-100 text-emerald-600 text-[7px] font-black">OK</span>`;
    const div=document.createElement('div');div.className=`bg-white border rounded-xl p-3 cursor-pointer hover:border-blue-400 transition-all ${stockBajo?'border-red-200':'border-slate-200'}`;div.onclick=()=>window.seleccionarProductoInventario(p.id);
    div.innerHTML=`<div class="flex justify-between items-start"><p class="font-black text-slate-800 uppercase text-[11px] tracking-tight leading-none">${p.nombre}</p>${badgeStock}</div><p class="text-[9px] text-slate-400 italic mt-0.5">${p.proveedor||'---'} · ${p.categoria||'---'}</p><div class="flex justify-between items-center mt-2"><span class="text-[9px] font-black text-slate-500 uppercase">Stock: <span class="${colorStock} text-[12px]">${p.cantidadStock||0}</span> ${p.unidad||'und'}</span><span class="text-[10px] font-black text-blue-700">$${parseFloat(p.precioVenta||0).toFixed(2)}</span></div>`;
    lista.appendChild(div);
  });
};

// ─── SELECCIONAR PRODUCTO ───
window.seleccionarProductoInventario = async (id) => {
  try{const snap=await getDoc(doc(db,"inventario",id));if(!snap.exists())return;const p=snap.data();window._productoEditandoId=id;
  const set=(elId,v)=>{const el=document.getElementById(elId);if(el)el.value=v??"";}
  set('invNombre',p.nombre);set('invProveedor',p.proveedor);set('invCategoria',p.categoria);set('invCostoCompra',p.costoCompra);set('invPrecioVenta',p.precioVenta);set('invStock',p.cantidadStock);set('invStockMinimo',p.stockMinimo);set('invUnidad',p.unidad);set('invDescripcion',p.descripcion);set('invFechaVence',p.fechaVencimiento);
  window.actualizarEstadoInventarioVisual();const titulo=document.getElementById('tituloFormInventario');if(titulo)titulo.innerText=`✏️ Editando: ${p.nombre}`;document.getElementById('formInventarioPanel')?.classList.remove('hidden');document.getElementById('btnEliminarProducto')?.classList.remove('hidden');document.getElementById('btnNuevoProducto')?.classList.remove('hidden');}
  catch(e){console.error(e);alert("❌ Error cargando producto.");}
};

// ─── GUARDAR PRODUCTO ───
window.guardarProductoInventario = async () => {
  const val=(id)=>document.getElementById(id)?.value.trim()||"";const num=(id)=>parseFloat(document.getElementById(id)?.value)||0;
  const nombre=val('invNombre');if(!nombre){alert("⚠️ El nombre es obligatorio.");return;}
  const data={nombre,proveedor:val('invProveedor'),categoria:val('invCategoria'),costoCompra:num('invCostoCompra'),precioVenta:num('invPrecioVenta'),cantidadStock:num('invStock'),stockMinimo:num('invStockMinimo')||3,unidad:val('invUnidad')||"und",descripcion:val('invDescripcion'),fechaVencimiento:val('invFechaVence'),ultimaActualizacion:serverTimestamp()};
  try{const id=window._productoEditandoId;if(id){await updateDoc(doc(db,"inventario",id),data);await addDoc(collection(db,"movimientos_inventario"),{productoId:id,productoNombre:nombre,tipo:"ACTUALIZACIÓN",cantidad:data.cantidadStock,fecha:serverTimestamp()});alert("✅ Producto actualizado.");}
  else{const ref=await addDoc(collection(db,"inventario"),{...data,fechaCreacion:serverTimestamp()});await addDoc(collection(db,"movimientos_inventario"),{productoId:ref.id,productoNombre:nombre,tipo:"INGRESO_INICIAL",cantidad:data.cantidadStock,fecha:serverTimestamp()});alert("✅ Producto creado.");}
  await window.cargarInventario();window.nuevoProductoInventario();}
  catch(e){console.error(e);alert("❌ Error: "+e.message);}
};

window.nuevoProductoInventario=()=>{window._productoEditandoId=null;['invNombre','invProveedor','invCategoria','invCostoCompra','invPrecioVenta','invStock','invStockMinimo','invUnidad','invDescripcion','invFechaVence'].forEach(id=>{const el=document.getElementById(id);if(el)el.value="";});const titulo=document.getElementById('tituloFormInventario');if(titulo)titulo.innerText="➕ Nuevo Producto";document.getElementById('btnEliminarProducto')?.classList.add('hidden');};

window.eliminarProductoInventario=async()=>{const id=window._productoEditandoId;if(!id){alert("⚠️ Selecciona un producto.");return;}const clave=prompt("🔐 CLAVE MAESTRA:");if(!clave)return;if(clave.trim()!==MASTER_KEY()){alert("🚫 Incorrecta.");return;}const nombre=document.getElementById('invNombre')?.value||"---";if(!confirm(`⚠️ Eliminar "${nombre}".\n¿Confirmas?`))return;try{await deleteDoc(doc(db,"inventario",id));if(typeof window.registrarLogAuditoria==='function')await window.registrarLogAuditoria("ELIMINACIÓN INVENTARIO",`Eliminó: ${nombre}`);alert(`✅ "${nombre}" eliminado.`);await window.cargarInventario();window.nuevoProductoInventario();}catch(e){console.error(e);alert("❌ Error: "+e.message);}};

window.filtrarInventario=()=>{const filtro=document.getElementById('filtroInventario')?.value.toLowerCase().trim()||"";if(!window._inventarioCache)return;const filtrados=filtro?window._inventarioCache.filter(p=>(p.nombre||"").toLowerCase().includes(filtro)||(p.proveedor||"").toLowerCase().includes(filtro)||(p.categoria||"").toLowerCase().includes(filtro)):window._inventarioCache;window.renderListaInventario(filtrados);};

window.actualizarSelectorProveedores=()=>{if(!window._inventarioCache)return;const proveedores=[...new Set(window._inventarioCache.map(p=>p.proveedor).filter(Boolean))];const sel=document.getElementById('filtroProveedor');if(!sel)return;sel.innerHTML=`<option value="">Todos los proveedores</option>`;proveedores.forEach(p=>{sel.innerHTML+=`<option value="${p}">${p}</option>`;});};

window.calcularPrecioFinalAvipet=()=>{const costo=parseFloat(document.getElementById('invCostoCompra')?.value)||0;const margen=parseFloat(document.getElementById('invMargen')?.value)||30;const precio=costo*(1+margen/100);const el=document.getElementById('invPrecioVenta');if(el)el.value=precio.toFixed(2);};

window.actualizarEstadoInventarioVisual=()=>{const stock=parseFloat(document.getElementById('invStock')?.value)||0;const minimo=parseFloat(document.getElementById('invStockMinimo')?.value)||3;const badge=document.getElementById('badgeEstadoStock');if(!badge)return;if(stock<=0){badge.innerText="AGOTADO";badge.className="px-2 py-0.5 rounded-full bg-red-200 text-red-800 text-[8px] font-black";}else if(stock<=minimo){badge.innerText="STOCK BAJO";badge.className="px-2 py-0.5 rounded-full bg-amber-100 text-amber-700 text-[8px] font-black";}else{badge.innerText="OK";badge.className="px-2 py-0.5 rounded-full bg-emerald-100 text-emerald-700 text-[8px] font-black";}};

window.mostrarAjusteRapido=()=>{document.getElementById('panelAjusteRapido')?.classList.toggle('hidden');};

window.aplicarAjusteRapido=async()=>{const id=window._productoEditandoId;if(!id){alert("⚠️ Selecciona un producto.");return;}const tipo=document.getElementById('tipoAjuste')?.value||"entrada";const cant=parseFloat(document.getElementById('cantAjuste')?.value)||0;const nota=document.getElementById('notaAjuste')?.value?.trim()||"";if(cant<=0){alert("Ingresa una cantidad válida.");return;}try{const snap=await getDoc(doc(db,"inventario",id));if(!snap.exists())return;const stockAct=parseFloat(snap.data().cantidadStock)||0;const nuevo=tipo==="entrada"?stockAct+cant:Math.max(0,stockAct-cant);await updateDoc(doc(db,"inventario",id),{cantidadStock:nuevo,ultimaActualizacion:serverTimestamp()});await addDoc(collection(db,"movimientos_inventario"),{productoId:id,productoNombre:snap.data().nombre,tipo:tipo==="entrada"?"ENTRADA":"SALIDA",cantidad:cant,stockAntes:stockAct,stockDespues:nuevo,nota,fecha:serverTimestamp()});const elStock=document.getElementById('invStock');if(elStock)elStock.value=nuevo;window.actualizarEstadoInventarioVisual();document.getElementById('panelAjusteRapido')?.classList.add('hidden');await window.cargarInventario();alert(`✅ Stock: ${nuevo} unidades.`);}catch(e){console.error(e);alert("❌ Error: "+e.message);}};

window.verMovimientosProducto=async()=>{const id=window._productoEditandoId;if(!id){alert("⚠️ Selecciona un producto.");return;}try{const snap=await getDocs(query(collection(db,"movimientos_inventario"),where("productoId","==",id),orderBy("fecha","desc")));if(snap.empty){alert("Sin movimientos registrados.");return;}let html=`<div style="max-height:320px;overflow-y:auto;"><table style="width:100%;border-collapse:collapse;font-size:10px;"><thead><tr style="background:#1e293b;color:#fff;"><th style="padding:6px 8px;text-align:left;">Fecha</th><th style="padding:6px 8px;text-align:center;">Tipo</th><th style="padding:6px 8px;text-align:center;">Cant</th><th style="padding:6px 8px;text-align:center;">Antes→Después</th><th style="padding:6px 8px;text-align:left;">Nota</th></tr></thead><tbody>`;snap.forEach(d=>{const r=d.data();const fecha=r.fecha?.toDate?r.fecha.toDate().toLocaleDateString():"---";const color=r.tipo?.includes("ENTRADA")?"#16a34a":"#dc2626";html+=`<tr style="border-bottom:1px solid #f1f5f9;"><td style="padding:5px 8px;">${fecha}</td><td style="padding:5px 8px;text-align:center;font-weight:900;color:${color};">${r.tipo}</td><td style="padding:5px 8px;text-align:center;font-weight:bold;">${r.cantidad}</td><td style="padding:5px 8px;text-align:center;font-size:9px;">${r.stockAntes??'---'}→${r.stockDespues??'---'}</td><td style="padding:5px 8px;font-style:italic;color:#64748b;">${r.nota||'-'}</td></tr>`;});html+=`</tbody></table></div>`;Swal.fire({title:'📊 Movimientos',html,width:680,showConfirmButton:true,confirmButtonText:'Cerrar'});}catch(e){console.error(e);alert("❌ Error: "+e.message);}};

window.descargarReporteProveedor=async()=>{try{const snap=await getDocs(collection(db,"inventario"));const filtroEl=document.getElementById('filtroProveedor');const filtro=filtroEl?.value||"";const datos=[];snap.forEach(d=>{const r=d.data();if(filtro&&r.proveedor!==filtro)return;datos.push({Nombre:r.nombre,Proveedor:r.proveedor||"---",Categoría:r.categoria||"---",Costo:r.costoCompra||0,PrecioVenta:r.precioVenta||0,Stock:r.cantidadStock||0,StockMínimo:r.stockMinimo||3,Unidad:r.unidad||"und",Vencimiento:r.fechaVencimiento||"---",Estado:(r.cantidadStock||0)<=(r.stockMinimo||3)?"BAJO":"OK"});});if(!datos.length){alert("No hay datos para el filtro.");return;}const hoja=XLSX.utils.json_to_sheet(datos);const libro=XLSX.utils.book_new();XLSX.utils.book_append_sheet(libro,hoja,filtro?`Proveedor_${filtro}`:"Inventario");XLSX.writeFile(libro,`Inventario_${(filtro||"Completo").replace(/\s+/g,'_')}_${new Date().toISOString().split('T')[0]}.xlsx`);}catch(e){console.error(e);alert("❌ Error: "+e.message);}};

// ─── PANEL CONFIG ───
window.renderizarTablaMaestra=async()=>{const cont=document.getElementById('tablaServiciosMaestro');if(!cont)return;cont.innerHTML=`<p class="text-center text-[9px] animate-pulse text-blue-500 font-black uppercase italic py-4">Cargando...</p>`;try{const snap=await getDocs(collection(db,"servicios_maestro"));if(snap.empty){cont.innerHTML=`<p class="text-center text-slate-400 text-[9px] italic py-4">Sin servicios.</p>`;return;}let html=`<table class="w-full text-left border-collapse"><thead><tr class="bg-slate-800 text-white text-[8px] uppercase font-black italic"><th class="p-2">Servicio</th><th class="p-2 text-center w-24">Precio ($)</th><th class="p-2 text-center w-20">% Doctor</th><th class="p-2 text-center w-16">OK</th></tr></thead><tbody class="text-[10px]">`;snap.forEach(d=>{const r=d.data();html+=`<tr class="border-b border-slate-100 hover:bg-blue-50"><td class="p-2 font-bold uppercase text-slate-700">${d.id}</td><td class="p-2 text-center"><input type="number" value="${r.precioVenta||0}" step="0.50" min="0" onblur="window.actualizarPrecioIndividual('${d.id}','precioVenta',this.value)" class="w-20 text-center border border-slate-300 rounded px-1 py-0.5 focus:border-blue-500 outline-none text-[10px]"></td><td class="p-2 text-center"><input type="number" value="${r.porcDoc||r.porcentajeDoc||30}" step="0.5" min="0" max="100" onblur="window.actualizarPrecioIndividual('${d.id}','porcDoc',this.value)" class="w-16 text-center border border-slate-300 rounded px-1 py-0.5 focus:border-blue-500 outline-none text-[10px]"></td><td class="p-2 text-center"><button onclick="window.actualizarPrecioIndividual('${d.id}','guardado',null,true)" class="text-[8px] px-2 py-1 bg-blue-600 text-white rounded font-black">✓</button></td></tr>`;});html+=`</tbody></table>`;cont.innerHTML=html;}catch(e){console.error(e);cont.innerHTML=`<p class="text-red-500 text-[9px] text-center italic py-4">❌ Error</p>`;}};

window.actualizarPrecioIndividual=async(nombreServicio,campo,valor,soloGuardar)=>{try{const snap=await getDoc(doc(db,"servicios_maestro",nombreServicio));const data=snap.exists()?snap.data():{};if(!soloGuardar)data[campo]=parseFloat(valor)||0;await setDoc(doc(db,"servicios_maestro",nombreServicio),data,{merge:true});if(typeof window.porcGlobalCache!=='undefined')window.porcGlobalCache=undefined;}catch(e){console.error("Error actualizando precio:",e);}};

window.renderizarTablaInsumos=async()=>{const cont=document.getElementById('tablaInsumosMaestro');if(!cont)return;cont.innerHTML=`<p class="text-center text-[9px] animate-pulse text-blue-500 font-black uppercase italic py-4">Cargando...</p>`;try{const snap=await getDocs(collection(db,"insumos_maestro"));if(snap.empty){cont.innerHTML=`<p class="text-center text-slate-400 text-[9px] italic py-4">Sin insumos.</p>`;return;}let html=`<table class="w-full text-left border-collapse"><thead><tr class="bg-slate-800 text-white text-[8px] uppercase font-black italic"><th class="p-2">Insumo</th><th class="p-2 text-center w-24">Costo ($)</th><th class="p-2 text-center w-16">✕</th></tr></thead><tbody class="text-[10px]">`;snap.forEach(d=>{const r=d.data();html+=`<tr class="border-b border-slate-100 hover:bg-emerald-50"><td class="p-2 font-bold italic text-slate-700">${r.nombre||d.id}</td><td class="p-2 text-center"><input type="number" value="${r.costo||0}" step="0.05" min="0" onblur="window.actualizarCostoInsumo('${d.id}',this.value)" class="w-20 text-center border border-slate-300 rounded px-1 py-0.5 focus:border-blue-500 outline-none text-[10px]"></td><td class="p-2 text-center"><button onclick="window.eliminarInsumoIndividual('${d.id}','${(r.nombre||d.id).replace(/'/g,'')}')" class="text-[8px] px-2 py-1 bg-red-100 text-red-600 rounded font-black hover:bg-red-600 hover:text-white transition-all">✕</button></td></tr>`;});html+=`</tbody></table>`;cont.innerHTML=html;}catch(e){console.error(e);cont.innerHTML=`<p class="text-red-500 text-[9px] text-center italic py-4">❌ Error</p>`;}};

window.actualizarCostoInsumo=async(idInsumo,valor)=>{try{await updateDoc(doc(db,"insumos_maestro",idInsumo),{costo:parseFloat(valor)||0,actualizadoEn:serverTimestamp()});}catch(e){console.error(e);}};

window.eliminarInsumoIndividual=async(idInsumo,nombreInsumo)=>{const clave=prompt(`🔐 Eliminar "${nombreInsumo}"\nCLAVE MAESTRA:`);if(!clave||clave.trim()!==MASTER_KEY()){alert("🚫 Clave incorrecta.");return;}if(!confirm(`⚠️ Eliminar "${nombreInsumo}".\n¿Confirmas?`))return;try{await deleteDoc(doc(db,"insumos_maestro",idInsumo));alert(`✅ Eliminado.`);window.renderizarTablaInsumos();}catch(e){console.error(e);alert("❌ Error: "+e.message);}};

// ─── INICIALIZAR BD ───
window.inicializarBaseDeDatosCompleta=async()=>{const clave=prompt("🔐 CLAVE MAESTRA:");if(!clave||clave.trim()!==MASTER_KEY()){alert("🚫 Clave incorrecta.");return;}if(!confirm("⚠️ ¿Inicializar catálogo de servicios en Firebase?"))return;
const SERVICIOS_DEFAULT={"CONSULTA GENERAL":{precioVenta:30,porcDoc:40},"CONSULTA OFTALMOLÓGICA":{precioVenta:80,porcDoc:12.5},"CONSULTA DE EMERGENCIA":{precioVenta:40,porcDoc:40},"ABSCESO":{precioVenta:25,porcDoc:50},"ECOGRAFÍA":{precioVenta:30,porcDoc:40},"COLOCACION VIA":{precioVenta:15,porcDoc:50},"ADMINISTRACION MEDICINA":{precioVenta:10,porcDoc:50},"TOMA DE MUESTRA SANGRE":{precioVenta:10,porcDoc:50},"VACUNA SEXTUPLE":{precioVenta:40,porcDoc:50},"VACUNA PUPPY":{precioVenta:40,porcDoc:50},"VACUNA ANTIRRÁBICA":{precioVenta:30,porcDoc:50},"VACUNA KC (TOS DE LAS PERRERAS)":{precioVenta:45,porcDoc:50},"VACUNA TRIPLE FELINA":{precioVenta:45,porcDoc:50},"VACUNA QUINTUPLE FELINA":{precioVenta:50,porcDoc:50},"VACUNA BIOVETA":{precioVenta:60,porcDoc:50},"HEMATOLOGÍA COMPLETA":{precioVenta:23,porcDoc:34.78},"QUÍMICA SANGUÍNEA":{precioVenta:60,porcDoc:50},"DESCARTE HEMOPARASITO":{precioVenta:50,porcDoc:50},"DISTEMPER":{precioVenta:35,porcDoc:50},"PARVOVIRUS - CORONAVIRUS":{precioVenta:35,porcDoc:50},"FILARIASIS":{precioVenta:40,porcDoc:50},"SIDA - LEUCEMIA":{precioVenta:40,porcDoc:50},"TEST HELICOBACTER PYLORI AG":{precioVenta:40,porcDoc:50},"HEMATOLOGIA + QUIMICA + HEMOPARASITOS":{precioVenta:110,porcDoc:50},"EXAMEN DE HECES":{precioVenta:10,porcDoc:50},"EXAMENES DE ORINA":{precioVenta:10,porcDoc:50},"CITOLOGIA 1 OIDO":{precioVenta:15,porcDoc:50},"CITOLOGIA 2 OIDOS":{precioVenta:20,porcDoc:50},"RASPADO PIEL":{precioVenta:10,porcDoc:50},"PERFIL ANEMICO":{precioVenta:25,porcDoc:17.5},"EUTANASIA HASTA 5KG":{precioVenta:80,porcDoc:50},"EUTANASIA HASTA 15KG":{precioVenta:110,porcDoc:50},"EUTANASIA HASTA 25KG":{precioVenta:140,porcDoc:50},"EUTANASIA HASTA 35KG":{precioVenta:170,porcDoc:50},"REFERIDO: EXAMEN DE HECES":{precioVenta:10,porcDoc:50},"REFERIDO: EXAMENES DE ORINA":{precioVenta:10,porcDoc:50},"REFERIDO: CULTIVOS":{precioVenta:30,porcDoc:50},"REFERIDO: DESCARTE HEMOPARASITO":{precioVenta:40,porcDoc:50},"REFERIDO: DISTEMPER":{precioVenta:35,porcDoc:50},"REFERIDO: PARVOVIRUS - CORONAVIRUS":{precioVenta:35,porcDoc:50},"CONSULTA CAMADA 3-4 CACHORROS":{precioVenta:50,porcDoc:40},"CONSULTA CAMADA HASTA 8 CACHORROS":{precioVenta:80,porcDoc:40},"CONSULTA CAMADA MAS DE 8 CACHORROS":{precioVenta:100,porcDoc:40}};
try{Swal.fire({title:'⏳ Inicializando...',allowOutsideClick:false,didOpen:()=>Swal.showLoading()});let cnt=0;for(const[nombre,datos]of Object.entries(SERVICIOS_DEFAULT)){await setDoc(doc(db,"servicios_maestro",nombre),{...datos,actualizadoEn:serverTimestamp()},{merge:true});cnt++;}Swal.close();alert(`✅ ${cnt} servicios inicializados.`);window.renderizarTablaMaestra();}catch(e){Swal.close();console.error(e);alert("❌ Error: "+e.message);}};

// ─── CAMBIAR SUB-TAB CONFIG ───
window.cambiarSubTabConfig=(tab)=>{'servicios,insumos,seguridad,tarifa'.split(',').forEach(t=>{const panel=document.getElementById('panel_subTab'+t.charAt(0).toUpperCase()+t.slice(1));const btn=document.getElementById('btn_subTab'+t.charAt(0).toUpperCase()+t.slice(1));const esActivo=t===tab;panel?.classList.toggle('hidden',!esActivo);if(btn){btn.className=esActivo?"text-[9px] px-3 py-1.5 font-black uppercase rounded-lg bg-blue-600 text-white":"text-[9px] px-3 py-1.5 font-black uppercase rounded-lg bg-slate-100 text-slate-600 hover:bg-blue-50";}});if(tab==='servicios')window.renderizarTablaMaestra();if(tab==='insumos')window.renderizarTablaInsumos();};

console.log("✅ inventario.js v2 cargado");
